In [1]:
import numpy as np

In [2]:
#python list
my_list = [1, 2, 3]

In [3]:
#numpy array
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
#nested list - 2D Matrices
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#also step size can be added
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones(4, 'int')

array([1, 1, 1, 1])

In [18]:
#Evenly spaced points in a range
#this function will return 10 equally spaced number in the given range[0,5]
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
#creating identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
#array of random number
np.random.rand(5)

array([0.9328496 , 0.17617433, 0.71499875, 0.10210245, 0.37425783])

In [21]:
np.random.rand(5, 5)

array([[0.98236245, 0.75368448, 0.95257289, 0.86516426, 0.71877081],
       [0.48679536, 0.90764168, 0.65469498, 0.24255965, 0.18674398],
       [0.86951139, 0.70974932, 0.37604193, 0.67101511, 0.16896851],
       [0.82608084, 0.2924588 , 0.54354791, 0.28900877, 0.98651768],
       [0.41943684, 0.09009442, 0.38920149, 0.84775715, 0.57259496]])

In [22]:
#returns random numbers from standrad normal dirtribution
np.random.randn(5)

array([-0.77794782, -0.72915938,  0.04011722, -1.50763915,  0.57365491])

In [23]:
#random integer from a range [a, n)
np.random.randint(1,100)

77

In [26]:
#random x integers from a range (a, n, x)
ranarr = np.random.randint(1,100, 10)

In [27]:
ranarr

array([88, 47, 21, 93, 49, 75, 28, 52, 36, 29])

In [34]:
#reshape array
reshaped_arr = ranarr.reshape(5,2) #5 * 2 == 10

In [31]:
ranarr.max()

93

In [32]:
ranarr.min()

21

In [36]:
reshaped_arr

array([[88, 47],
       [21, 93],
       [49, 75],
       [28, 52],
       [36, 29]])

In [41]:
ranarr.argmax()

3

In [43]:
ranarr[3]

93

In [44]:
reshaped_arr.shape

(5, 2)

In [45]:
ranarr.dtype

dtype('int32')

In [55]:
#indexing and slicing numpy array
#indexing start at 0 (zero)
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [58]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr[:6] #same as arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [65]:
arr[5:] ##same as arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
#change value in the given range
arr[1:5] = 100

In [69]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [70]:
slice_of_arr = arr[1:6]

In [71]:
slice_of_arr


array([100, 100, 100, 100,   5])

In [72]:
slice_of_arr[:] = 99

In [73]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [75]:
#so slice_of_arr is just view of orginal arr, it's not a copy
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [76]:
arr_copy = arr.copy()

In [77]:
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
arr_copy

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_copy[1:4] = -2

In [80]:
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [81]:
arr_copy

array([ 0, -2, -2, -2, 99, 99,  6,  7,  8,  9, 10])

In [82]:
#conditional logics in array
arr = np.arange(1, 11)

In [83]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
bool_arr = arr > 5

In [85]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [87]:
#only get the results where bool array is happened to be true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [90]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [89]:
arr[arr < 3]

array([1, 2])

In [92]:
arr_2d = np.arange(50).reshape(5,10)

In [93]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [95]:
arr_2d[2][3]

23

In [96]:
arr_2d[2, 3]

23

In [99]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [100]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [102]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [103]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [104]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
arr ** 3


array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [106]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])